import "./globals.css";
import { getServerSession } from "next-auth";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/lib/SessionProvider";
import {  Poppins } from 'next/font/google' 


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({weight:'400', subsets: ['latin'] });

export default async function RootLayout({ children }) {

  const session = await getServerSession();
  
  
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider session={session}>
            {children}
            <Toaster />
          </AuthProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
